---
title: "Web Accessibility 101"
subtitle: "Making Research and Geospatial Applications Inclusive"
---

PowerPoint slides, links, and additional content will all be linked to from this page ahead of the workshop.

## Abstract

This introductory workshop covers essential web accessibility principles for researchers creating public web applications, particularly geospatial tools. No prior accessibility experience required. Learn basic inclusive design practices, practical implementation techniques, and be inspired to put accessibility first when designing applications!

## Description

This workshop is aimed at absolute beginners when it comes to accessible design; the content is very introductory and will centre “first steps” and the idea of web accessibility as a constant work in progress.

We will have interactive polls and Q&A, but will not be coding. You can use a laptop or a smartphone to interact with the polls.

## Note submitted by author with abstract

While this workshop is informed by some delivery team members’ experience, if there is another proposal for a workshop on accessibility being delivered by a disabled researcher, we would like to defer to them instead. However, in the absence of another session being proposed on web accessibility, we would be delighted to deliver this session.

# Examples

- [Font size (opens in a new tab)](accessibility/html/fonts.html){target="_blank"}
- [Keyboard navigation test (opens in a new tab)](accessibility/html/tabfocus_test.html){target="_blank"}
- [Keyboard navigation answers (opens in a new tab)](accessibility/html/tabfocus.html){target="_blank"}
- [Bad design exercise (opens in a new tab). WARNING - slow flashing text.](accessibility/html/bad-design.html){target="_blank"}